github-org-name: nyu-database-design
github-repo-name: course-materials
baseurl: /course-materials
title: Database Design & Implementation
description: >
  A fantastic voyage through designing databases for practical implementation
copyright: GNU General Public License, Version 3
layouts_dir: theme/_layouts/
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
defaults:
  - scope:
      path: "content"
      type: pages
    values:
      layout: github
  - scope:
      path: "slides"
      type: pages
    values:
      layout: presentation
